version: '3'
services:
  # TODO: PUT SERVICE NAME HERE. good to match project/repo name.
  # Running th startup-compose.sh script will automatically replace this.
  testing:
    container_name: jupyter
    user: root
    privileged: true
    build: .
    restart: always
    volumes:
      #- ./notebooks:/home/jovyan/notebooks
      #- ./data:/home/jovyan/data
      # This ensures we can just have the key in one central location for local and on docker
      # If this image ends up being pushed to the cloud, then the file must be copied.
      - $HOME/.aws/credentials:/home/jovyan/.aws/credentials:ro
    environment:
      - GRANT_SUDO=yes
      # Allows Jupyter Lab to start
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8558:8558"